easy_admin:
    entities:
        Episode:
            class: App\Entity\Episode
            list:
                sort: 'numberForSort'
                fields:
                - { property: 'backgroundImageUrl', fileProperty: 'backgroundImageFile', template: 'vich_uploader_image.html.twig' }
                - { property: 'pristineMediaUrl', fileProperty: 'pristineMediaFile', template: 'vich_uploader_audio.html.twig' }
            form:
                fields:
                    - { property: 'backgroundImageFile', type: 'file' }
                    - { property: 'pristineMediaFile', type: 'file' }
