# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        episodes_adapter:
            local:
                directory: '%kernel.project_dir%/../uploads.thatpodcast/episodes'
    filesystems:
        episode_filesystem:
            adapter: episodes_adapter
            alias: League\Flysystem\Filesystem
            mount: episode_filesystem
