parameters:
    env(GOOGLE_ANALYTICS_TRACKING_ID): ~
    google_analytics_tracking_id: '%env(resolve:GOOGLE_ANALYTICS_TRACKING_ID)%'
twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        GOOGLE_ANALYTICS_TRACKING_ID: '%google_analytics_tracking_id%'