parameters:
    app.path.uploads: "http://uploads.thatpodcast.test"

vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        episode_background_image:
            uri_prefix: "%app.path.uploads%/episodes"
            upload_destination: "episode_filesystem"
            directory_namer:
                service: "vich_uploader.namer_directory_property"
                options: { property: 'backgroundImageDirectory', transliterate: true}

        episode_pristine_media:
            uri_prefix: "%app.path.uploads%/episodes"
            upload_destination: "episode_filesystem"
            directory_namer:
                service: "vich_uploader.namer_directory_property"
                options: { property: 'pristineMediaDirectory', transliterate: true}
