# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        content:
            local:
                directory: '%kernel.project_dir%/../uploads.thatpodcast'
    filesystems:
        content:
            adapter: content
            alias: League\Flysystem\Filesystem
