# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        content:
            awss3v3:
                client: flysystem.s3.client
                bucket: '%flysystem.s3.bucket%'
                prefix: ~
    filesystems:
        content:
            adapter: content
            alias: League\Flysystem\Filesystem
