#index:
#    path: /
#    controller: App\Controller\DefaultController::index
newsletter:
    path: /newsletter
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: newsletter.html.twig

about:
    path: /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: about.html.twig

logout:
    path: /logout
